# Use Ubuntu 22.04 as the base image
FROM devopsdockeruh/simple-web-service:alpine

# Install curl
#RUN apt-get update && apt-get install -y curl

# Set working directory
#WORKDIR /usr/src/app

# Copy the script file into the container
COPY script.sh .

# Give execute permissions to the script
RUN chmod +x script.sh

# Set the script to run on container start
CMD ["server"]

